// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfAppDentikMVVM_Core.Data;

#nullable disable

namespace WpfAppDentikMVVM_Core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220806180756_TestModel")]
    partial class TestModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("WpfAppDentikMVVM_Core.Model.DataPrice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("fees")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("option")
                        .HasColumnType("INTEGER");

                    b.Property<string>("problemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("treatOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("dataPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
